#pragma once

#define WIN32_LEAN_AND_MEAN //avoid 

#define BT_DETECT_DURATION_SECONDS 10 //10 seconds
#define BT_SERVICE_SEARCH_DURATION_SECONDS 20 //Arbitraty...20 seconds
#define BT_DETECT_INTERVAL_MS 3*1000
#define BT_SERVICE_SEARCH_INTERVAL_MS 5000

#define BT_DEV_MGR_MAX_CONCURRENT_ACCESS 100 //Not used
#define BT_DEV_MGR_ROUTINE_INTERVAL_MS 10*1000 //10 seconds


#define MON_THREAD_CHECK_INTERVAL_MS 30*1000 //30 seconds