#pragma once

#define BT_DETECT_DURATION_SECONDS 20
#define BT_DETECT_INTERVAL_MS 3000

#define BT_DEV_MGR_MAX_CONCURRENT_ACCESS 100 //Not used
#define BT_DEV_MGR_ROUTINE_INTERVAL_MS 2000 //Not used


#define MON_THREAD_CHECK_INTERVAL_MS 30*1000 //30 seconds